Fixed error in user-login-form spec file
Test cases in userLogin-form spec file failed with below error,
Error: Cannot read property 'root' of undefined.

This error was because, activated route was not injected into the
testingbed. Fixed this error.

Issue-ID: APPC-1064
Change-Id: Ib9978b73be744204e8dd64b97abbc0959a4e5839
Signed-off-by: Arundathi Patil <arundpil@in.ibm.com>